### ISSUE TITLE
OneConfig

### ISSUE THREAD

**Issue by Larestan67** [BananaFructa/Apec#43]
So i recently instaled this W of a mod and was wondering how to edit the gui spots on oneconfig as your default editing menu is not availible

**Comment by CaidenBlock** [comment]
HUD isn't being handled by oneconfig at the moment, only toggles.

Add a keybind in settings for 'Apec Settings Menu' (not GUI), press that.

I'd recommend you don't mess with the settings in this menu due to potential conflicts with oneconfig, but you can open the gui by pressing the button in the top left and edit it as normal.

**Comment by Hexeption** [comment]
fixed in 1.12.1
